---
title: "Analasis of AUDPC - question 2"
author: "Can Plant Think"
date: "2023-12-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Helianthus Annuus : AUDPC question 2

## Library

```{r library}
library(ggplot2)
library(agricolae)
library(patchwork)
```

## Importation and datas
```{r datas}
data_temoin <- read.csv("C:\\Users\\33646\\OneDrive\\Documents\\Autres dossiers\\Sup Agro\\2ème année\\Recherche\\R\\ATS1P2_angles_result_training.csv", header = T, sep= ",")

data_perturb <- read.csv("C:\\Users\\33646\\OneDrive\\Documents\\Autres dossiers\\Sup Agro\\2ème année\\Recherche\\R\\ATS1P2_angles_result_training.csv", header = T, sep= ",")

result_audpc_temoin <- data.frame(track = character(), "Angle L1G.L1D" = numeric(), "Angle L2G.L2D" = numeric(), "Angle L1.Y" = numeric(), "Angle L2.Y" = numeric(), "Angle IN.Y" = numeric(), stringsAsFactors = FALSE)
result_audpc_perturb <- data.frame(track = character(), "Angle L1G.L1D" = numeric(), "Angle L2G.L2D" = numeric(), "Angle L1.Y" = numeric(), "Angle L2.Y" = numeric(), "Angle IN.Y" = numeric(), stringsAsFactors = FALSE)

result_Student <- data.frame("Angle L1G.L1D" = rep(0, times = 10), "Angle L2G.L2D" = rep(0, times = 10), "Angle L1.Y" = rep(0, times = 10), "Angle L2.Y" = rep(0, times = 10), "Angle IN.Y" = rep(0, times = 10), stringsAsFactors = FALSE)
rownames(result_Student) <- c("shapiro_temoin_W","shapiro_temoin_p_value", "shapiro_perturb_W","shapiro_perturb_p_value", "variance_W", "variance_p_value", "student_t", "student_p_value", "student_interval_low", "student_interval_high")
```

# Question 2 : difference in angles between positions

## AUDPC

```{r AUDPC_2, echo = false}
low = list(2,6,10) #maybe change here too
high = list(5,9,13) #and here

for (position in 1:3) {
  column_indices <- c(low[[position]]:high[[position]], 1) #verify time
  cname <- c("Angle L1G.L1D", "Angle L2G.L2D", "Angle L1.Y","Angle L2.Y", "Angle IN.Y", "time")
  position_data_t <- data_temoin[, column_indices, drop = FALSE]
  colnames(position_data_t) <-  cname
  position_data_p <- data_perturb[, column_indices, drop = FALSE]
  colnames(position_data_p) <-  cname

  #transforming time in a different class so it's possible to plot
  position_data_t$time <- as.POSIXct(position_data_t[, 5], format = "%Y-%m-%d %H:%M:%S")
  position_data_p$time <- as.POSIXct(position_data_p[, 5], format = "%Y-%m-%d %H:%M:%S")

  
  
  pos_t <- list(track = paste0("track_",track), "Angle.L1G.L1D" = 0, "Angle.L2G.L2D" = 0, "Angle.L1.Y" = 0, "Angle.L2.Y" = 0, "Angle.IN.Y" = 0)
  pos_p <- list(track = paste0("track_",track), "Angle.L1G.L1D" = 0, "Angle.L2G.L2D" = 0, "Angle.L1.Y" = 0, "Angle.L2.Y" = 0, "Angle.IN.Y" = 0)

  # plot
   plot_t <- ggplot(data = position_data_t, aes(x = time))
  if (!all(is.na(position_data_t[, "Angle L1G.L1D"]))) {
    plot_t <- plot_t + geom_line(aes(y = position_data_t[, "Angle L1G.L1D"], color = "Angle L1G.L1D"), size = 1) 
  }
  if (!all(is.na(position_data_t[, "Angle L2G.L2D"]))) {
    plot_t <- plot_t + geom_line(aes(y = position_data_t[, "Angle L2G.L2D"], color = "Angle L2G.L2D"), size = 1)
  }
  if (!all(is.na(position_data_t[, "Angle L1.Y"]))) {
    plot_t <- plot_t + geom_line(aes(y = position_data_t[, "Angle L1.Y"], color = "Angle L1.Y"), size = 1)
  }
  if (!all(is.na(position_data_t[, "Angle L2.Y"]))) {
    plot_t <- plot_t + geom_line(aes(y = position_data_t[, "Angle L2.Y"], color = "Angle L2.Y"), size = 1)
  }
  if (!all(is.na(position_data_t[, "Angle IN.Y"]))) {
    plot_t <- plot_t + geom_line(aes(y = position_data_t[, "Angle IN.Y"], color = "Angle IN.Y"), size = 1)
  }
    plot_t <- plot_t + 
      scale_color_manual(name = "Angle", values = c("#e78847","#05a894", "#dda0dd", "#2a52be", "#F7DC6F")) +
    labs(title = paste("Angle against time for sunflowers in position ", position, "in normal conditions"), x = "Time", y ="Angle")

  plot_p <- ggplot(data = position_data_p, aes(x = time))
   if (!all(is.na(position_data_p[, "Angle L1G.L1D"]))) {
    plot_p <- plot_p + geom_line(aes(y = position_data_p[, "Angle L1G.L1D"], color = "Angle L1G.L1D"), size = 1) 
  }
  if (!all(is.na(position_data_p[, "Angle L2G.L2D"]))) {
    plot_p <- plot_p + geom_line(aes(y = position_data_p[, "Angle L2G.L2D"], color = "Angle L2G.L2D"), size = 1)
  }
  if (!all(is.na(position_data_p[, "Angle L1.Y"]))) {
    plot_p <- plot_p + geom_line(aes(y = position_data_p[, "Angle L1.Y"], color = "Angle L1.Y"), size = 1)
  }
  if (!all(is.na(position_data_p[, "Angle L2.Y"]))) {
    plot_p <- plot_p + geom_line(aes(y = position_data_p[, "Angle L2.Y"], color = "Angle L2.Y"), size = 1)
  }
  if (!all(is.na(position_data_p[, "Angle IN.Y"]))) {
    plot_p <- plot_p + geom_line(aes(y = position_data_p[, "Angle IN.Y"], color = "Angle IN.Y"), size = 1)
  }
  plot_p <- plot_p + 
    scale_color_manual(name = "Angle", values = c("#e78847","#05a894", "#dda0dd", "#2a52be", "#F7DC6F")) +
    labs(title = paste("Angle against time for sunflowers in position", position, "in changed conditions"), x = "Time", y = "Angle")

  grid <- plot_t + plot_p + plot_layout(ncol = 1, heights = c(1, 1)) +
    plot_annotation(title = paste("Difference in angles between normal and changed conditions in position", position, "for sunflowers"))
  print(grid)

  # audpc
  for (i in 1:5) {
    audpc_result_t <- ifelse(all(is.na(position_data_t[, i])), NA, audpc(position_data_t[, i], position_data_t$time, type = "absolute"))
    audpc_result_p <- ifelse(all(is.na(position_data_p[, i])), NA, audpc(position_data_p[, i], position_data_p$time, type = "absolute"))

    pos_t[i+1] <- audpc_result_t
    pos_p[i+1] <- audpc_result_p
  }

  result_audpc_temoin <- rbind(result_audpc_temoin, pos_t)
  result_audpc_perturb <- rbind(result_audpc_perturb, pos_p)
}


print(result_audpc_temoin)
```

## Analysis of the results - Student test

```{r Student_2, echo = false}
for (i in 2:5) {
  data_t <- as.numeric(result_audpc_temoin[[i]])
  data_p <- as.numeric(result_audpc_perturb[[i]])
  
  complete_cases <- complete.cases(data_t, data_p)
  data_t <- data_t[complete_cases]
  data_p <- data_p[complete_cases]
  #verifying normality
  result_Student["shapiro_temoin_p_value", i-1] <- shapiro.test(data_t)$p.value 
  result_Student["shapiro_temoin_W", i-1] <- shapiro.test(data_t)$statistic
  result_Student["shapiro_perturb_p_value", i-1] <- shapiro.test(data_p) 
  result_Student["shapiro_perturb_W", i-1] <- shapiro.test(data_t)$statistic
  
  #variance test
  result_Student["variance_p_value", i-1] <- var.test(data_t, data_p)$p.value
  result_Student["variance_W", i-1] <- var.test(data_t, data_p)$statistic

  #Student test when the variables are 
  result_Student["student_p_value", i-1] <- t.test(data_t,data_p, paired=T)$p.value
  result_Student["student_t", i-1] <- t.test(data_t,data_p, paired=T)$statistic
  result_Student["student_interval_low", i-1] <- t.test(data_t,data_p, paired=T)$conf.int[1]
  result_Student["student_interval_high", i-1] <- t.test(data_t,data_p, paired=T)$conf.int[2]

}

print(result_Student)

```
