---
title: "Analysis of the AUDPC - question 3"
author: "Can Plant Think"
date: "2023-12-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Arabidopsis Thaliana : AUDPC question 3

## Library

```{r library}
library(ggplot2)
library(agricolae)
library(patchwork)
```

## Importation and datas
```{r datas}
data_temoin <- read.csv("C:\\Users\\33646\\OneDrive\\Documents\\Autres dossiers\\Sup Agro\\2ème année\\Recherche\\R\\ATS1P2_angles_result_training.csv", header = T, sep= ",")[17:21]
data_temoin <- cbind(data_temoin, data_temoin[2:5]+15, data_temoin[2:5]*1.05)
data_perturb <- read.csv("C:\\Users\\33646\\OneDrive\\Documents\\Autres dossiers\\Sup Agro\\2ème année\\Recherche\\R\\ATS1P2_angles_result_training.csv", header = T, sep= ",")[17:21]
data_perturb <- cbind(data_perturb, data_perturb[2:5]+15, data_temoin[2:5]*1.05)

result_audpc_temoin <- data.frame(track = character(), "Angle 1E.4E" = numeric(), "Angle 2I.3I" = numeric(), "Angle E.Y" = numeric(), "Angle I.Y" = numeric(), stringsAsFactors = FALSE)
result_audpc_perturb <- data.frame(track = character(), "Angle 1E.4E" = numeric(), "Angle 2I.3I" = numeric(), "Angle E.Y" = numeric(), "Angle I.Y" = numeric(), stringsAsFactors = FALSE)

result_Student <- data.frame("Angle 1E.4E" = rep(0, times = 10), "Angle 2I.3I" = rep(0, times = 10), "Angle E.Y" = rep(0, times = 10), "Angle I.Y" = rep(0, times = 10), stringsAsFactors = FALSE)
rownames(result_Student) <- c("shapiro_temoin_W","shapiro_temoin_p_value", "shapiro_perturb_W","shapiro_perturb_p_value", "variance_W", "variance_p_value", "student_t", "student_p_value", "student_interval_low", "student_interval_high")
```
# Question 3 : difference in angles between species

## AUDPC

```{r AUDPC_2, echo = false}
low = list(2,6,10)
high = list(5,9,13)

for (position in 1:3) {
  column_indices <- c(low[[position]]:high[[position]], 1)
  cname <- c("Angle 1E.4E", "Angle 2I.3I", "Angle E.Y", "Angle I.Y", "time")
  position_data_t <- data_temoin[, column_indices, drop = FALSE]
  colnames(position_data_t) <-  cname
  position_data_p <- data_perturb[, column_indices, drop = FALSE]
  colnames(position_data_p) <-  cname

  #transforming time in a different class so it's possible to plot
  position_data_t$time <- as.POSIXct(position_data_t[, 5], format = "%Y-%m-%d %H:%M:%S")
  position_data_p$time <- as.POSIXct(position_data_p[, 5], format = "%Y-%m-%d %H:%M:%S")

  
  
  pos_t <- list(position = paste0("position_", position), "Angle.1E.4E" = 0, "Angle.2I.3I" = 0, "Angle.E.Y" = 0, "Angle.I.Y" = 0)
  pos_p <- list(position = paste0("position_", position), "Angle.1E.4E" = 0, "Angle.2I.3I" = 0, "Angle.E.Y" = 0, "Angle.I.Y" = 0)

  # plot
  plot_t <- ggplot(data = position_data_t, aes(x = time))
  if (!all(is.na(position_data_t[, "Angle 1E.4E"]))) {
    plot_t <- plot_t + geom_line(aes(y = position_data_t[, "Angle 1E.4E"], color = "Angle 1E.4E"), size = 1)
  }
  if (!all(is.na(position_data_t[, "Angle 2I.3I"]))) {
    plot_t <- plot_t + geom_line(aes(y = position_data_t[, "Angle 2I.3I"], color = "Angle 2I.3I"), size = 1)
  }
  if (!all(is.na(position_data_t[, "Angle E.Y"]))) {
    plot_t <- plot_t + geom_line(aes(y = position_data_t[, "Angle E.Y"], color = "Angle E.Y"), size = 1)
  }
  if (!all(is.na(position_data_t[, "Angle I.Y"]))) {
    plot_t <- plot_t + geom_line(aes(y = position_data_t[, "Angle I.Y"], color = "Angle I.Y"), size = 1)
  }
  plot_t <- plot_t +
    scale_color_manual(name = "Angle", values = c("#e78847","#05a894", "#dda0dd", "#2a52be")) +
    labs(title = paste("Angle against time for plants in position ", position, "in normal conditions"), x = "Time", y ="Angle")

  plot_p <- ggplot(data = position_data_p, aes(x = time))
  if (!all(is.na(position_data_p[, "Angle 1E.4E"]))) {
    plot_p <- plot_p + geom_line(aes(y = position_data_p[, "Angle 1E.4E"], color = "Angle 1E.4E"), size = 1)
  }
  if (!all(is.na(position_data_p[, "Angle 2I.3I"]))) {
    plot_p <- plot_p + geom_line(aes(y = position_data_p[, "Angle 2I.3I"], color = "Angle 2I.3I"), size = 1)
  }
  if (!all(is.na(position_data_p[, "Angle E.Y"]))) {
    plot_p <- plot_p + geom_line(aes(y = position_data_p[, "Angle E.Y"], color = "Angle E.Y"), size = 1)
  }
  if (!all(is.na(position_data_p[, "Angle I.Y"]))) {
    plot_p <- plot_p + geom_line(aes(y = position_data_p[, "Angle I.Y"], color = "Angle I.Y"), size = 1)
  }
  plot_p <- plot_p +
    scale_color_manual(name = "Angle", values = c("#e78847","#05a894", "#dda0dd", "#2a52be")) +
    labs(title = paste("Angle against time for plants in position", position, "in changed conditions"), x = "Time", y = "Angle")

  grid <- plot_t + plot_p + plot_layout(ncol = 1, heights = c(1, 1)) +
    plot_annotation(title = paste("Difference in angles between normal and changed conditions in position", position))
  print(grid)

  # audpc
  for (i in 1:4) {
    audpc_result_t <- ifelse(all(is.na(position_data_t[, i])), NA, audpc(position_data_t[, i], position_data_t$time, type = "absolute"))
    audpc_result_p <- ifelse(all(is.na(position_data_p[, i])), NA, audpc(position_data_p[, i], position_data_p$time, type = "absolute"))

    pos_t[i+1] <- audpc_result_t
    pos_p[i+1] <- audpc_result_p
  }

  result_audpc_temoin <- rbind(result_audpc_temoin, pos_t)
  result_audpc_perturb <- rbind(result_audpc_perturb, pos_p)
}


print(result_audpc_temoin)
```